import { jsPDF } from "jspdf";

const PURPLE = [130, 36, 227];
const PURPLE_LIGHT = [216, 187, 246];
const DARK = [19, 4, 34];
const MUTED = [112, 111, 131];
const SURFACE = [251, 249, 253];
const BORDER = [232, 224, 240];
const RED = [204, 51, 51];

export function downloadPayslipPdf({ companyName, employeeName, periodLabel, grossPay, deductions, netPay }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = 595;
  const marginX = 50;
  const contentW = pageW - marginX * 2;

  // ---- Header band ----
  doc.setFillColor(...DARK);
  doc.rect(0, 0, pageW, 118, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.setTextColor(255, 255, 255);
  doc.text(companyName || "HRhub", marginX, 56);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...PURPLE_LIGHT);
  doc.text("HR, organized.", marginX, 74);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...PURPLE_LIGHT);
  doc.text("PAYSLIP", pageW - marginX, 56, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(periodLabel, pageW - marginX, 74, { align: "right" });

  // ---- Info card ----
  let y = 150;
  doc.setFillColor(...SURFACE);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(1);
  doc.roundedRect(marginX, y, contentW, 74, 10, 10, "FD");

  const colW = contentW / 3;
  const infoItems = [
    ["EMPLOYEE", employeeName],
    ["PAY PERIOD", periodLabel],
    ["ISSUED", new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })],
  ];
  infoItems.forEach(([label, value], i) => {
    const x = marginX + 24 + i * colW;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text(label, x, y + 28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...DARK);
    doc.text(String(value), x, y + 48);
  });

  // ---- Breakdown table ----
  y += 74 + 40;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text("EARNINGS & DEDUCTIONS", marginX, y);

  y += 16;
  const rowH = 38;
  const rows = [
    { label: "Gross pay", sub: "Base compensation for this period", amount: grossPay, negative: false },
    { label: "Deductions", sub: "Taxes and other withholdings", amount: deductions, negative: true },
  ];

  rows.forEach((row, i) => {
    const rowY = y + i * rowH;
    if (i % 2 === 0) {
      doc.setFillColor(...SURFACE);
      doc.rect(marginX, rowY, contentW, rowH, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...DARK);
    doc.text(row.label, marginX + 16, rowY + 17);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    doc.text(row.sub, marginX + 16, rowY + 30);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11.5);
    doc.setTextColor(...(row.negative ? RED : DARK));
    const formatted = `${row.negative ? "-" : ""}NGN ${Math.abs(row.amount).toLocaleString()}`;
    doc.text(formatted, marginX + contentW - 16, rowY + 24, { align: "right" });
  });

  doc.setDrawColor(...BORDER);
  doc.setLineWidth(1);
  doc.rect(marginX, y, contentW, rowH * rows.length);

  // ---- Net pay highlight ----
  y += rowH * rows.length + 20;
  doc.setFillColor(...PURPLE);
  doc.roundedRect(marginX, y, contentW, 60, 10, 10, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...PURPLE_LIGHT);
  doc.text("NET PAY", marginX + 20, y + 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text(`NGN ${netPay.toLocaleString()}`, marginX + contentW - 20, y + 38, { align: "right" });

  // ---- Footer ----
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text(
    "This payslip was generated by HRhub. Please contact your HR administrator with any questions.",
    marginX,
    780
  );

  const filename = `payslip-${periodLabel.replace(/\s+/g, "-").toLowerCase()}.pdf`;
  doc.save(filename);
}